### ISSUE TITLE
alpine-base no longer allows installing packages: database file format error

### ISSUE THREAD

**Issue by 4x0v7** [wolfi-dev/tools#9]
**Description**

Previously I was using `cgr.dev/chainguard/alpine-base:latest` as a base image. I could use `apk add` to add additional packages as needed.
After I saw it moved with https://github.com/chainguard-images/images/pull/255 I started using `ghcr.io/wolfi-dev/alpine-base:latest`

I've found now though, that running `apk update` or `apk add` results in:
```
ERROR: FDB format error (line 485, entry 'R')
ERROR: Unable to read database state: database file format error
ERROR: Failed to open apk database: database file format error
```

Specifically I found this with `ghcr.io/wolfi-dev/alpine-base@sha256:bd6f7e822b65777a1fb1e6b08bc6656eae26436515844ec87c6ef69a4294fc22`

Was this an intended change?
Am I better off moving to apko to build an image with the specific packages I need?

**Comment by patflynn** [comment]
@amouat I'm guessing P2. Feel free to change.  We should clarify why this image exists in the repo.

**Comment by amouat** [comment]
We don't support alpine-base any more. Please use wolfi-base and let us know if there's a reason you need alpine-base.

**Comment by amouat** [comment]
This should be fixed now if you pull the new image.
